name: CheckStyle

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Analyze code with Checkstyle
        run: mvn checkstyle:check

      - name: JAR file
        run: mvn clean package

      # not sure about this :(
      - name: Add artifact jar
        uses: actions/upload-artifact@v2
        with:
            name: project-jar
            path: target/*.jar